### ISSUE TITLE
Key column 'session_id' doesn't exist in table

### ISSUE THREAD

**Issue by SolarisYan** [nitmir/django-cas-server#1]
my python version is Python 2.7.6 and django version is Django (1.9.4), 
i only use the django-admin startproject xx to create the project,
when i execute the commad python manage.py migrate,the error come,

/software/python/venv/cas/local/lib/python2.7/site-packages/cas_server/urls.py:46: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url('^auth$', views.Auth.as_view(), name='auth'),

Operations to perform:
  Apply all migrations: admin, contenttypes, cas_server, auth, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK
  Applying cas_server.0001_squashed_0021_auto_20150611_2102...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/software/python/venv/cas/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1072, "Key column 'session_id' doesn't exist in table")

anyone can help me?

**Comment by nitmir** [comment]
I think I know that the problem is:
```
$ python -V
Python 2.7.11+
$ pip freeze
Django==1.9.4
argparse==1.2.1
django-bootstrap3==7.0.1
django-cas-server==0.4.3
django-picklefield==0.3.2
futures==3.0.5
lxml==3.6.0
requests==2.9.1
requests-futures==0.9.7
wsgiref==0.1.2
```

```
$ ./manage.py migrate
/tmp/django-cas-server/test_venv/local/lib/python2.7/site-packages/cas_server/urls.py:46: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url('^auth$', views.Auth.as_view(), name='auth'),

Operations to perform:
  Apply all migrations: admin, contenttypes, cas_server, auth, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK
  Applying cas_server.0001_squashed_0021_auto_20150611_2102... OK
  Applying cas_server.0002_auto_20151212_1300... OK
  Applying cas_server.0003_auto_20151212_1721... OK
  Applying cas_server.0004_auto_20151218_1032... OK
```

I have the line `Applying sessions.0001_initial... OK` and you do not. Before commit 77fc5b59885fcba2e9a02b96789cff09fde9806a only the SQL session bakend was supported and the migrations are reflecting that. I should squash migrations again.

In the mean time, you can try to enable SQL session backend just for the initial migration.

**Comment by nitmir** [comment]
Sorry, I misread your logs, you have the  `Applying sessions.0001_initial... OK`, so I don't know.

Can you send me your settings.py (with `SECRET_KEY` and possible databases passwords anonymized) so I can try to reproduce ?

**Comment by nitmir** [comment]
Ok, I have the same error then using the MySQL backend

**Comment by nitmir** [comment]
I edit by hand the first migration and it should now work. 

Indeed before commit 77fc5b59885fcba2e9a02b96789cff09fde9806a the User model had a foreign key to the Session model. After the commit, we just store the `session_key`, allowing to use different backend than the Session SQL backend.
So the first migration (which is 21 migrations combined)  was creating the User model with the foreign key, then delete it and add the field `session_key`. Somehow, MySQL did not like it. So I edited to migration to directly create the User model with the `session_key` and without the foreign key to  the Session SQL backend.

**Comment by SolarisYan** [comment]
that's ok,thank you.
Before use this , i used the yale java version CAS Server,but i use django except the cas server,now i will use django-cas-server in my project,maybe i will have some other problem
