### ISSUE TITLE
Initial run of collectstatic in non-debug mode fails

### ISSUE THREAD

**Issue by takkaria** [nitmir/django-cas-server#38]
**Summary:**

When using `django-cas-server`, you have to run `collectstatic` in debug mode before you can run it in non-debug mode .  Otherwise you get the following backtrace:

```
$ python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "<venv path>/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "<venv path>/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "<venv path>/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<venv path>/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "<venv path>/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "<venv path>/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<venv path>/lib/python3.6/site-packages/cas_server/models.py", line 13, in <module>
    from .default_settings import settings, SessionStore
  File "<venv path>/lib/python3.6/site-packages/cas_server/default_settings.py", line 21, in <module>
    CAS_LOGO_URL = static("cas_server/logo.png")
  File "<venv path>/lib/python3.6/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 12, in static
    return _static(path)
  File "<venv path>/lib/python3.6/site-packages/django/templatetags/static.py", line 166, in static
    return StaticNode.handle_simple(path)
  File "<venv path>/lib/python3.6/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "<venv path>/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "<venv path>/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "<venv path>/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'cas_server/logo.png'
```

**Analysis:**

When `django-cas-server` module gets loaded, its default settings use the template tag `static` to find out where its default logo is.  In debug mode, this function just returns the path to the file without any other faff. [[1]](https://github.com/django/django/blob/master/django/contrib/staticfiles/storage.py#L117)

However, in non-debug mode, it tries to search the staticfiles manifest for the file.  If there is no manifest because `collectstatic` has not been run before, this fails.

**Workaround:**

At the moment you can work around this by running `collectstatic` in debug mode before turning it off.  This isn't ideal in production though.

**Comment by takkaria** [comment]
Thanks, it seems to be working.  (Any chance of a release sometime soon?)
